Fix link error on (at least) OpenSUSE Tumbleweed
/usr/lib64/libopcodes.a(i386-dis.o): in function 'putop': ~~~/binutils-2.37/opcodes/i386-dis.c:10331: undefined reference to_sch_istable

Simply swapping Binutils::Iberty and Binutils::Opcodes would fix this,
but would likely break with older versions of binutils.
So the idea is -liberty -lopcodes -liberty to have both permutations.
But simply using cmake targets twice doesn't give us that, cmake
deduplicates. So I have to resort to using a different syntax to append
-liberty again. Ugly, but seems to work.