Missing include: ansidecl.h
Need ansidecl.h (presumably this picks up libiberty's header)
to fix compile errors like

/usr/local/include/bfd.h:1745:38: error: expected ')'
bfd_set_section_userdata (bfd * abfd ATTRIBUTE_UNUSED, asection * ptr,

where ATTRIBUTE_UNUSED comes from ansidecl.h.